---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: taskapp
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAWdZx065XcbJ26MUVFeI9bhtW+/GLLXIfayqI1YwgQwUCwO1EV64IJl2OskNuft3QUCKimdw4TrYRcOT4PDIaqNSQckP5FwmIxTpN5ZDlzixBPtG3bDRJFFoywB0EzTkljUMw5utjk86SZaCH59ufdkUmiePenKen7VC+OK96P4V5Q60x9Kb6Snl1yEdyxaDFUZAG6yuW4GqitMXM+H24GO98HgvE4zPH+iubIxPaAAEUU4yml2yEYDiQHNJmeoxdRguGrxYuGK1Mr4piUqk7LjLyQBU87QjSNcTeXZ4JR0Og6Y1JCe4fJw1XqkhhZe0b1XeiQtfQ/12h2VM6Rz0HV/ctDoAgOJW1Ee+nHsc3mVwQsarmz3DOIlZvQ+IMGJek9UReiMG1cdvnCaZAPQhKUeRiCO/QPuBUI9zYCup7rJUZtQnW02HC1kuQSN9m4cG2uV6uArnL2+4bGpxKOHAAvp4eGNDFcPmwxheqSFT5CcsmpqJVVABvNcKIbZwoBX2J/C2k7O/A3tp2ukSX7J0o7SwhVm+2u8PkiZRWRly1XOfOB55wlwglbVkYkyh2JhR2N/NrEFUAfaP8xQc8HgqvhauY4VxWnKVxSgBFMp3pVgWSIgGLoU+WcSUn8r4imB+k5XiNa7gygzGd7g9cp1l+otq9N+el9tclaytDTHbCPYCDU9VVX+6etTNVrMcBeoDeQ7dMy5lx6WbofdLddnosE1Og=
    POSTGRES_USER: AgB9PzLdq23R4Yh+YSDHKOA1Gt/ZEa6jNuY/f3/4mrVAm3WJHd979SrEPyHWa921hqOLulGuUO8LzWQPSMrquaSkNWomhffGnJFP6jfU5BOEqOlHdQME+qs2TOnToDJh8xTD5iMVRBuhYox7GTvcxC++mCjJ5CuHQiaiZSR53EijK+zYsXRwEzvZbT0lYkGvZhjD5NI3la1CaS7vATwiLpxwfUwAlmwMg8szHozx8/QX4z6RWHLTOdbNMLMA7wI4zGsfTgQwtDpjUCLE3tBxNKlAUDa9O2W9tIfIRt3WaFDkRX0rIrNXx7ysC4pifU6HvkNn57xXOc7sPBbEWD33v5McVe9s2DHHPwqWh6zFqhIPdpLVMaFtosUNMeLaDiyUqeGLEVhaW2qq627SimsI9pg/hkSaV/JK6jTmLrbaIAljWy/YeE4aK7Qn8RwdiqovelZoUNeNFzKkiQE6HUbszAUBZ3AarQYbCiy1ctSxTGlis9kVzmRQTP0qpDKY0DvlysKfUgB54KH25+dNrJ145YWZxGqmk8WMp7Di2O9zvG0lqovj8XP/fZbsd56fjNjpz7//DC4iE/jXX+IW/k1zZvZwLZ1GyYA5In18lz1wLHP+iX+rGpzzVU7WVKrEOE5nqFywlhyTcgN+U8pOwsAkOdM2/ktAQ7DEVJxEWmMLmvjbAdByMFoGBNvHtik2fgWG1bAbH3SeCSBk
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: taskapp
